// <auto-generated />
using Mango.Services.ProductApi.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mango.Services.ProductApi.Migrations
{
    [DbContext(typeof(ApplicationDbContexts))]
    partial class ApplicationDbContextsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mango.Services.ProductApi.Models.Dtos.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categoryname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("imageurl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Categoryname = "Appetizer",
                            Description = "Praesent scelerisque, mi sed ultrices condimentum",
                            Name = "Samosa",
                            Price = 15.0,
                            imageurl = "https://dotnetmistry75.blob.core.windows.net/mango/download%20(4).jpg"
                        },
                        new
                        {
                            ProductId = 2,
                            Categoryname = "Appetizer",
                            Description = "Praesent scelerisque, mi sed ultrices condimentum",
                            Name = "Paneer Tikka",
                            Price = 13.99,
                            imageurl = "https://dotnetmistry75.blob.core.windows.net/mango/download (5).jpg"
                        },
                        new
                        {
                            ProductId = 3,
                            Categoryname = "Appetizer",
                            Description = "Praesent scelerisque, mi sed ultrices condimentum",
                            Name = "Sweet Pie",
                            Price = 11.0,
                            imageurl = "https://dotnetmistry75.blob.core.windows.net/mango/download (6).jpg"
                        },
                        new
                        {
                            ProductId = 4,
                            Categoryname = "Appetizer",
                            Description = "Praesent scelerisque, mi sed ultrices condimentum",
                            Name = "Pav Bhaji",
                            Price = 15.0,
                            imageurl = "https://dotnetmistry75.blob.core.windows.net/mango/images (1).jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
